import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from './components/Sidebar';
import UserMiddleware from './middleware/page';
import Login from './auth/login/page';
// import Login from './auth/login/page';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Task Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
// @ts-ignore:next-line
//   let token ;

//   if (typeof window !== 'undefined') {
//     // Perform localStorage action
//     token = JSON.parse(localStorage.getItem('token'))
// console.log(token)

//   }
// console.log(token)
  return (
    <html lang="fr">
      <body className={inter.className}>
        <UserMiddleware>
      <Sidebar/>
      {children}

     
        </UserMiddleware>
      </body>
    </html>
  )
}
